python od_flow_clustering.py -i "data/2.xlsx" -k 5
python od_flow_clustering.py -i "data/2.xlsx" -k 10
python od_flow_clustering.py -i "data/2.xlsx" -k 15
python od_flow_clustering.py -i "data/2.xlsx" -k 20
python od_flow_clustering.py -i "data/2.xlsx" -k 25
python od_flow_clustering.py -i "data/2.xlsx" -k 30
python od_flow_clustering.py -i "data/2.xlsx" -k 40
python od_flow_clustering.py -i "data/2.xlsx" -k 50
python od_flow_clustering.py -i "data/2.xlsx" -k 100
python od_flow_clustering.py -i "data/2.xlsx" -k 150
python od_flow_clustering.py -i "data/2.xlsx" -k 200
python od_flow_clustering.py -i "data/2.xlsx" -k 500