python od_flow_clustering.py -i "data/2.xlsx" -k 10
python od_flow_clustering.py -i "data/2.xlsx" -k 25
python od_flow_clustering.py -i "data/2.xlsx" -k 50
python od_flow_clustering.py -i "data/2.xlsx" -k 100
python od_flow_clustering.py -i "data/2.xlsx" -k 200
python od_flow_clustering.py -i "data/2.xlsx" -k 300
python od_flow_clustering.py -i "data/2.xlsx" -k 400
python od_flow_clustering.py -i "data/2.xlsx" -k 500
python od_flow_clustering.py -i "data/2.xlsx" -k 600
python od_flow_clustering.py -i "data/2.xlsx" -k 700
python od_flow_clustering.py -i "data/2.xlsx" -k 800
python od_flow_clustering.py -i "data/2.xlsx" -k 900
python od_flow_clustering.py -i "data/2.xlsx" -k 1000
python od_flow_clustering.py -i "data/2.xlsx" -k 1200
python od_flow_clustering.py -i "data/2.xlsx" -k 1500